[package]
name = "fps"
version = "0.1.0"
edition = "2024"


[dependencies]
raylib = { path = "/home/bqrry/Desktop/raylib-rs/raylib" }
enet = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"